Repository vergecurrency/vWallet, pull requests merged in 2018-07, with the labels that each got.

#28 Restyle welcome guide
  src/ReRouter.tsx
  src/assets/css/app-title-bar.scss
  src/assets/css/form.scss
  src/assets/css/main.scss
  src/assets/css/tour.scss
  src/assets/css/variables.scss
  src/mainRoute.tsx
  src/routes.tsx
  src/stores/SetupStore.ts
  src/welcomeguide/AnimationTarget.js
  src/welcomeguide/Buy.js
  src/welcomeguide/Finalize.js
  src/welcomeguide/Step.js
  src/welcomeguide/Welcome.js
  src/welcomeguide/wallet/PasswordConfirm.js
  src/welcomeguide/wallet/PasswordCreate.js
Labels: Design, Development, Frontend

#29 Adding a general multilanguage
  package.json
  src/assets/css/tour.scss
  src/components/AccountBar.tsx
  src/components/Footer.tsx
  src/components/Header/BurgerMenu.tsx
  src/components/Statistics.tsx
  src/components/modal/CreditsPanel.js
  src/components/modal/DebugPanel.tsx
  src/components/modal/ReceivePanel.tsx
  src/components/modal/SendPanel.tsx
  src/components/modal/UnlockPanel.js
  src/components/settings/KeymapsPanel.tsx
  src/components/settings/SettingsPanel.tsx
  src/components/settings/settingItems/CurrencySetting.tsx
  src/components/settings/settingItems/RegionSetting.tsx
  src/components/transaction/SearchBar.js
  src/components/transaction/Transaction.tsx
  src/components/transaction/TransactionList.js
  src/containers/App.tsx
  src/index.d.ts
  src/routes.tsx
  src/stores/SettingsStore.ts
  src/translations/da.json
  src/translations/de.json
  src/translations/en.json
  src/translations/i18n.ts
  src/translations/locales.js
  src/translations/localesResources.ts
  src/translations/nl.json
  src/welcomeguide/ProgressBar.js
  src/welcomeguide/Step.js
  src/welcomeguide/Welcome.js
  yarn.lock
Labels: Translations

#33 Restyled the tooltip component
  src/assets/css/main.scss
  src/assets/css/tooltip.scss
Labels: Frontend

#32 Add no transactions yet info
  src/assets/css/account-bar.scss
  src/assets/css/home-page.scss
  src/assets/images/no-transactions.svg
  src/components/AccountBar.tsx
  src/components/transaction/TransactionList.js
  src/stores/TransactionStore.ts
  src/translations/en.json
  src/translations/nl.json
Labels: Frontend, enhancement

#34 Add balance to low information
  src/assets/css/send-modal.scss
  src/components/Modal.tsx
  src/components/modal/SendPanel.tsx
  src/translations/en.json
  src/translations/nl.json
Labels: Development, Frontend, enhancement

#35 Fix translations
  src/components/Header/Header.tsx
  src/components/modal/SendPanel.tsx
  src/translations/da.json
  src/translations/en.json
  src/translations/nl.json
Labels: Frontend, Translations

#36 Add donate modal
  src/assets/css/donate-modal.scss
  src/assets/css/form.scss
  src/assets/css/main.scss
  src/assets/css/modal.scss
  src/assets/css/receive-modal.scss
  src/components/Footer.tsx
  src/components/modal/DonatePanel.tsx
  src/components/modal/SendPanel.tsx
  src/components/transaction/AmountInput.tsx
  src/components/transaction/BalanceBar.tsx
  src/components/transaction/SendTransactionButton.tsx
  src/translations/en.json
  src/utils/Fee.ts
  src/utils/SendState.ts
Labels: Development, enhancement

#38 No donations when zero balance or wallet locked
  src/assets/css/donate-modal.scss
  src/assets/css/main.scss
  src/assets/css/no-balance-panel.scss
  src/assets/css/send-modal.scss
  src/components/Footer.tsx
  src/components/modal/DebugPanel.tsx
  src/components/modal/DonatePanel.tsx
  src/components/modal/NoBalancePanel.tsx
  src/components/modal/SendPanel.tsx
Labels: enhancement

#44 Verge client mock
  README.md
  build/VolumeIcon.icns
  build/background.png
  build/background@2x.png
  build/icon.icns
  build/tor/darwin/tor
  build/tor/darwin/tor-gencert
  build/tor/darwin/tor-resolve
  build/tor/darwin/torify
  build/tor/torrc
  build/tor/win32/libeay32.dll
  build/tor/win32/libevent-2-0-5.dll
  build/tor/win32/libevent_core-2-0-5.dll
  build/tor/win32/libevent_extra-2-0-5.dll
  build/tor/win32/libgcc_s_sjlj-1.dll
  build/tor/win32/libssp-0.dll
  build/tor/win32/ssleay32.dll
  build/tor/win32/tor-gencert.exe
  build/tor/win32/tor.exe
  build/tor/win32/zlib1.dll
  main.js
  package.json
  src/assets/css/app-title-bar.scss
  src/containers/App.tsx
  src/dev-config.json.example
  src/stores/VergeClient.ts
  src/utils/mockups/MockClient.ts
  yarn.lock
Labels: Backend, enhancement

#50 Adding key commands
  src/components/AccountBar.tsx
  src/components/Header/Header.tsx
  src/dev-config.json.example
Labels: enhancement

#51 Unifiying code for sending transactions
  src/components/modal/DonatePanel.tsx
  src/components/modal/ISendPanel.tsx
  src/components/modal/SendPanel.tsx
  src/stores/AccountInformationStore.ts
Labels: Backend, Improvement
